#################################################################
# +-----------------------------------------------------------+ #
# |                    kkutbot config file                    | #
# +-----------------------------------------------------------+ #
#################################################################

# kkutbot configuration file.
# encoding: utf-8


# run configuration
# 'true' to run testbot, 'false' to run the main bot.
test: true

# secret tokens
token:
  main: main bot token
  test: test bot token
  koreanbots: koreanbots api token
  dbl: top.gg api token
  uniquebots: uniquebots api token

# list of bot ids that can use kkutbot.
bot_whitelist:
  - 00000

# list of admin ids that can use admin commands.
admin:
  - 00000
  - 00000

# channel id that kkutbot logs
log_channel: 00000

# embed colors
colors:
  general: 0x4374D9
  error: 0xCC3D3D
  help: 0x47C83E

# mongodb configuration
mongo:
  ip: mongoDB server ip
  user: mongoDB username
  password: mongoDB passwd

# emoji name & id that kkutbot uses (emojis in official support server)
emojis:
  starter: 715559187756875807
  silver: 715548873975922788
  s_medal: 794532325068898334
  rate: 715834446883979379
  points: 715547592578170880
  m_master: 715558227944931349
  jem: 770866355528007702
  help: 715549237022163005
  gold: 715548900697702420
  admin: 751967819398381738
  bronze: 715548840643657739
  denyed: 730319627623596032
  done: 716902844975808606

# useful links
links:
  invite:
    bot: https://discord.com/api/oauth2/authorize?client_id=703956235900420226&permissions=387136&scope=bot
    server: https://discord.gg/z8tRzwf
  monitoring:
    pm2: pm2 monitoring url
    mongo: mongoDB monitoring url
  korenbots: https://koreanbots.dev/bots/703956235900420226
  dbl: https://top.gg/bot/703956235900420226
  uniquebots: https://uniquebots.kr/bots/info/703956235900420226
  blog: https://kkutbot.github.io

# users defauld data schema
default_data:
  _id: null
  _name: null
  register_date: null
  info_word: 소개말이 없습니다.
  points: 1000
  token: 0
  start_point: false
  daily:
    '0': false
    '1': false
    '2': false
    '3': false
    '4': false
    '5': false
    '6': false
  game:
    rank_solo:
      times: 0
      win: 0
      best: 0
      tier: 언랭크
    rank_multi:
      times: 0
      win: 0
      best: 0
      tier: 언랭크
    kkd:
      times: 0
      win: 0
      best: 0
    guild_multi:
      times: 0
      win: 0
      best: 0
    online_multi:
      times: 0
      win: 0
      best: 0
    apmal:
      times: 0
      win: 0
      best: 0
  daily_times: 0
  command_used: 0
  banned: false
  last_command: null
  mail: []
  alert:
    daily: false
    start_point: false
    mail: true

# group of game modes
modelist:
  솔로 랭킹전: rank_solo
  멀티 랭킹전: rank_multi
  쿵쿵따: kkd
  서버 다인전: guild_multi
  온라인 다인전: online_multi
  앞말잇기: apmal

# group of tier info & standard
tierlist:
  언랭크:
    points: 0
    winrate: 0
    times: 0
    emoji: ':sob:'
  뉴비:
    points: 1500
    winrate: 30
    times: 20
    emoji: <:rate:715834446883979379>
  브론즈:
    points: 3000
    winrate: 40
    times: 50
    emoji: <:bronze:715548840643657739>
  실버:
    points: 5000
    winrate: 55
    times: 75
    emoji: <:silver:715548873975922788>
  골드:
    points: 7500
    winrate: 70
    times: 100
    emoji: <:gold:715548900697702420>
  마스터:
    points: 10000
    winrate: 80
    times: 200
    emoji: <:m_master:715558227944931349>

# discord permissions en-ko translation
perms:
  create_instant_invite: 초대 코드 만들기
  kick_members: 멤버 추방하기
  ban_members: 멤버 차단하기
  administrator: 관리자
  manage_channels: 채널 관리하기
  manage_guild: 서버 관리하기
  add_reactions: 반응 추가하기
  view_audit_log: 감사 로그 보기
  priority_speaker: 우선 발언권
  stream: 동영상
  read_messages: 채팅 채널 읽기
  send_messages: 메시지 보내기
  send_tts_messages: TTS 메시지 보내기
  manage_messages: 메시지 관리
  embed_links: 링크 첨부
  attach_files: 파일 첨부
  read_message_history: 메시지 기록 보기
  mention_everyone: '@everyone @here 모든 역할 멘션하기'
  external_emojis: 외부 이모티콘 사용하기
  view_guild_insights: 서버 통계 확인하기
  connect: 연결
  speak: 말하기
  mute_members: 멤버들의 마이크 음소거하기
  deafen_members: 멤버의 헤드셋 음소거하기
  move_members: 멤버 이동
  use_voice_activation: 음성 감지 사용
  change_nickname: 별명 변경하기
  manage_nicknames: 별명 관리하기
  manage_roles: 역할 관리하기
  manage_webhooks: 웹후크 관리하기
  manage_emojis: 이모티콘 관리
  use_slash_commands: 빗금 명령어 사용
  request_to_speak: 발언권 신청
